ISSUE: KERNAL CRASH


Visual Studio Code (1.84.2, undefined, desktop)
Jupyter Extension Version: 2023.10.1003070148.
Python Extension Version: 2023.20.0.
Platform: win32 (x64).
Workspace folder ~\lumin_eye, Home = c:\Users\Biancaa. R
17:57:35.896 [info] Start refreshing Kernel Picker (1699705655896)
17:57:35.907 [info] Using Pylance
17:57:37.072 [info] End refreshing Kernel Picker (1699705655896)
17:57:40.758 [info] Start refreshing Kernel Picker (1699705660758)
17:57:41.764 [info] End refreshing Kernel Picker (1699705660758)
17:57:42.510 [info] Process Execution: d:\Anaconda\python.exe -m pip list
18:20:11.213 [info] Start refreshing Interpreter Kernel Picker
18:20:11.213 [info] Start refreshing Kernel Picker (1699707011213)
18:20:11.290 [warn] No interpreter for Pylance for Notebook URI "~\lumin_eye\model1.ipynb"
18:20:11.324 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd088279d2366fe020547cde40dd65aa0e3aa662a6ec1f3ca12d88834876c85e1a6.d:\Anaconda\python.exe.d:\Anaconda\python.exe.-m#ipykernel_launcher  (Python Path: d:\Anaconda\python.exe, Conda, base, 3.11.4) for '~\lumin_eye\model1.ipynb' (disableUI=true)
18:20:14.156 [info] Process Execution: d:\Anaconda\python.exe -m pip list
18:20:14.312 [info] Process Execution: d:\Anaconda\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
18:20:14.322 [info] Process Execution: d:\Anaconda\python.exe "~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py" --ppid 2240
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\pythonFiles\vscode_datascience_helpers
18:20:14.463 [info] Process Execution: d:\Anaconda\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"2c186649-809d-470a-abba-a6f6c356a277" --shell=9002 --transport="tcp" --iopub=9004 --f="~\AppData\Roaming\jupyter\runtime\kernel-v2-2240CDuj5n5In2QN.json"
    > cwd: ~\lumin_eye
18:20:14.746 [info] ipykernel version & path 6.25.0, d:\Anaconda\Lib\site-packages\ipykernel\__init__.py for d:\Anaconda\python.exe
18:20:15.581 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
18:20:15.618 [info] End refreshing Kernel Picker (1699707011213)
18:20:15.706 [warn] StdErr from Kernel Process d:\Anaconda\Lib\site-packages\traitlets\traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-2240CDuj5n5In2QN.json' instead of '"c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-2240CDuj5n5In2QN.json"' if you require traitlets >=5.
18:20:16.048 [info] Process Execution: d:\Anaconda\python.exe "~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\pythonFiles\printJupyterDataDir.py"
18:20:16.103 [warn] Got a non-existent Jupyer Data Dir file:///c%3A/Users/Biancaa.%20R/AppData/Roaming/Python/share/jupyter
18:20:16.575 [error] Widget Error: Failed to access CDN https://unpkg.com/ after 0 attempt(s), TypeError: Failed to fetch
18:45:05.697 [info] Handle Execution of Cells 1 for ~\lumin_eye\model1.ipynb
18:45:05.720 [info] Kernel acknowledged execution of cell 1 @ 1699708505718
18:45:06.753 [info] End cell 1 execution @ 1699708506753, started @ 1699708505718, elapsed time = 1.035s
18:45:08.972 [info] Handle Execution of Cells 2 for ~\lumin_eye\model1.ipynb
18:45:08.988 [info] Kernel acknowledged execution of cell 2 @ 1699708508988
18:45:19.147 [info] End cell 2 execution @ 1699708519147, started @ 1699708508988, elapsed time = 10.159s
18:45:22.650 [info] Handle Execution of Cells 3 for ~\lumin_eye\model1.ipynb
18:45:22.662 [info] Kernel acknowledged execution of cell 3 @ 1699708522662
18:45:22.663 [info] End cell 3 execution @ 1699708522663, started @ 1699708522662, elapsed time = 0.001s
18:45:26.219 [info] Handle Execution of Cells 4 for ~\lumin_eye\model1.ipynb
18:45:26.232 [info] Kernel acknowledged execution of cell 4 @ 1699708526232
18:45:26.246 [warn] StdErr from Kernel Process 2023-11-11 18:45:26.244815: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
18:45:28.546 [info] End cell 4 execution @ 1699708528546, started @ 1699708526232, elapsed time = 2.314s
18:45:35.685 [info] Handle Execution of Cells 7 for ~\lumin_eye\model1.ipynb
18:45:35.701 [info] Kernel acknowledged execution of cell 7 @ 1699708535701
18:45:35.927 [info] End cell 7 execution @ 1699708535927, started @ 1699708535701, elapsed time = 0.226s
18:45:41.973 [info] Handle Execution of Cells 10 for ~\lumin_eye\model1.ipynb
18:45:41.999 [info] Kernel acknowledged execution of cell 10 @ 1699708541999
18:45:42.032 [info] End cell 10 execution @ 1699708542032, started @ 1699708541999, elapsed time = 0.033s
18:45:45.823 [info] Handle Execution of Cells 11 for ~\lumin_eye\model1.ipynb
18:45:45.841 [info] Kernel acknowledged execution of cell 11 @ 1699708545841
18:45:45.908 [info] End cell 11 execution @ 1699708545908, started @ 1699708545841, elapsed time = 0.067s
18:45:48.985 [info] Handle Execution of Cells 12 for ~\lumin_eye\model1.ipynb
18:45:49.004 [info] Kernel acknowledged execution of cell 12 @ 1699708549004
18:45:49.005 [info] End cell 12 execution @ 1699708549005, started @ 1699708549004, elapsed time = 0.001s
18:45:51.704 [info] Handle Execution of Cells 13 for ~\lumin_eye\model1.ipynb
18:45:51.720 [info] Kernel acknowledged execution of cell 13 @ 1699708551720
18:45:51.720 [info] End cell 13 execution @ 1699708551720, started @ 1699708551720, elapsed time = 0s
18:45:54.901 [info] Handle Execution of Cells 14 for ~\lumin_eye\model1.ipynb
18:45:54.941 [info] Kernel acknowledged execution of cell 14 @ 1699708554941
18:45:54.987 [info] End cell 14 execution @ 1699708554986, started @ 1699708554941, elapsed time = 0.045s
18:45:57.534 [info] Handle Execution of Cells 15 for ~\lumin_eye\model1.ipynb
18:45:57.552 [info] Kernel acknowledged execution of cell 15 @ 1699708557552
18:45:57.558 [info] End cell 15 execution @ 1699708557558, started @ 1699708557552, elapsed time = 0.006s
18:46:00.126 [info] Handle Execution of Cells 16 for ~\lumin_eye\model1.ipynb
18:46:00.142 [info] Kernel acknowledged execution of cell 16 @ 1699708560142
18:46:00.558 [info] End cell 16 execution @ 1699708560558, started @ 1699708560142, elapsed time = 0.416s
18:46:03.137 [info] Handle Execution of Cells 17 for ~\lumin_eye\model1.ipynb
18:46:03.153 [info] Kernel acknowledged execution of cell 17 @ 1699708563153
18:46:03.155 [info] End cell 17 execution @ 1699708563155, started @ 1699708563153, elapsed time = 0.002s
18:46:06.601 [info] Handle Execution of Cells 18 for ~\lumin_eye\model1.ipynb
18:46:06.620 [info] Kernel acknowledged execution of cell 18 @ 1699708566620
18:46:06.621 [info] End cell 18 execution @ 1699708566621, started @ 1699708566620, elapsed time = 0.001s
18:46:09.715 [info] Handle Execution of Cells 19 for ~\lumin_eye\model1.ipynb
18:46:09.734 [info] Kernel acknowledged execution of cell 19 @ 1699708569734
18:46:10.411 [info] End cell 19 execution @ 1699708570411, started @ 1699708569734, elapsed time = 0.677s
18:47:35.762 [info] Handle Execution of Cells 19 for ~\lumin_eye\model1.ipynb
18:47:35.848 [info] Kernel acknowledged execution of cell 19 @ 1699708655848
18:47:37.129 [info] End cell 19 execution @ 1699708657129, started @ 1699708655848, elapsed time = 1.281s
18:47:41.393 [info] Handle Execution of Cells 19 for ~\lumin_eye\model1.ipynb
18:47:41.412 [info] Kernel acknowledged execution of cell 19 @ 1699708661412
18:47:42.457 [info] End cell 19 execution @ 1699708662457, started @ 1699708661412, elapsed time = 1.045s
18:47:45.942 [info] Handle Execution of Cells 20 for ~\lumin_eye\model1.ipynb
18:47:45.978 [info] Kernel acknowledged execution of cell 20 @ 1699708665978
18:47:46.845 [info] End cell 20 execution @ 1699708666845, started @ 1699708665978, elapsed time = 0.867s
18:47:46.845 [warn] Cancel all remaining cells due to cancellation or failure in execution
18:47:58.870 [info] Handle Execution of Cells 20 for ~\lumin_eye\model1.ipynb
18:47:58.908 [info] Kernel acknowledged execution of cell 20 @ 1699708678908
23:52:39.376 [info] End cell 20 execution @ 1699726959376, started @ 1699708678908, elapsed time = 18280.468s
23:52:46.254 [info] Handle Execution of Cells 21 for ~\lumin_eye\model1.ipynb
23:52:46.290 [info] Kernel acknowledged execution of cell 21 @ 1699726966290
23:52:46.420 [info] End cell 21 execution @ 1699726966420, started @ 1699726966290, elapsed time = 0.13s
23:52:49.998 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
23:52:50.017 [info] Kernel acknowledged execution of cell 22 @ 1699726970017
23:52:50.042 [info] End cell 22 execution @ 1699726970042, started @ 1699726970017, elapsed time = 0.025s
23:52:50.042 [warn] Cancel all remaining cells due to cancellation or failure in execution
23:53:01.935 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
23:53:01.952 [info] Kernel acknowledged execution of cell 22 @ 1699726981952
23:53:01.967 [info] End cell 22 execution @ 1699726981967, started @ 1699726981952, elapsed time = 0.015s
23:53:01.967 [warn] Cancel all remaining cells due to cancellation or failure in execution
23:54:03.728 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
23:54:03.746 [info] Kernel acknowledged execution of cell 22 @ 1699727043746
23:54:03.760 [info] End cell 22 execution @ 1699727043760, started @ 1699727043746, elapsed time = 0.014s
23:54:03.760 [warn] Cancel all remaining cells due to cancellation or failure in execution
23:57:45.295 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
23:57:45.314 [info] Kernel acknowledged execution of cell 22 @ 1699727265314
23:57:45.330 [info] End cell 22 execution @ 1699727265330, started @ 1699727265314, elapsed time = 0.016s
23:57:45.330 [warn] Cancel all remaining cells due to cancellation or failure in execution
23:59:44.861 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
23:59:44.882 [info] Kernel acknowledged execution of cell 22 @ 1699727384882
23:59:44.885 [info] End cell 22 execution @ 1699727384885, started @ 1699727384882, elapsed time = 0.003s
23:59:44.885 [warn] Cancel all remaining cells due to cancellation or failure in execution
23:59:51.206 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
23:59:51.227 [info] Kernel acknowledged execution of cell 22 @ 1699727391227
23:59:51.642 [info] End cell 22 execution @ 1699727391642, started @ 1699727391227, elapsed time = 0.415s
23:59:51.642 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:00:12.732 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:00:12.750 [info] Kernel acknowledged execution of cell 22 @ 1699727412750
00:00:12.910 [info] End cell 22 execution @ 1699727412910, started @ 1699727412750, elapsed time = 0.16s
00:00:12.910 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:00:33.844 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:00:33.881 [info] Kernel acknowledged execution of cell 22 @ 1699727433881
00:00:33.929 [info] End cell 22 execution @ 1699727433929, started @ 1699727433881, elapsed time = 0.048s
00:00:33.929 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:01:30.809 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:01:30.822 [info] Kernel acknowledged execution of cell 22 @ 1699727490822
00:01:30.869 [info] End cell 22 execution @ 1699727490869, started @ 1699727490822, elapsed time = 0.047s
00:01:30.869 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:04:17.431 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:04:17.449 [info] Kernel acknowledged execution of cell 22 @ 1699727657449
00:04:17.561 [info] End cell 22 execution @ 1699727657561, started @ 1699727657449, elapsed time = 0.112s
00:04:17.561 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:04:50.099 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:04:50.113 [info] Kernel acknowledged execution of cell 22 @ 1699727690113
00:04:50.165 [info] End cell 22 execution @ 1699727690165, started @ 1699727690113, elapsed time = 0.052s
00:04:50.165 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:05:21.909 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:05:21.926 [info] Kernel acknowledged execution of cell 22 @ 1699727721926
00:05:21.976 [info] End cell 22 execution @ 1699727721976, started @ 1699727721926, elapsed time = 0.05s
00:05:21.976 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:07:40.264 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:07:40.301 [info] Kernel acknowledged execution of cell 22 @ 1699727860301
00:07:40.349 [info] End cell 22 execution @ 1699727860349, started @ 1699727860301, elapsed time = 0.048s
00:07:40.349 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:09:10.658 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:09:10.679 [info] Kernel acknowledged execution of cell 22 @ 1699727950678
00:09:10.692 [info] End cell 22 execution @ 1699727950692, started @ 1699727950678, elapsed time = 0.014s
00:09:10.692 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:09:49.096 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:09:49.115 [info] Kernel acknowledged execution of cell 22 @ 1699727989115
00:09:59.047 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.046281: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_
00:09:59.047 [warn] StdErr from Kernel Process shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:09:59.409 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.408846: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:09:59.416 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.416502: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output sh
00:09:59.416 [warn] StdErr from Kernel Process apes may be inaccurate.
00:09:59.659 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.659381: W tensorflow/
00:09:59.659 [warn] StdErr from Kernel Process core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:09:59.771 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.771492: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be
00:09:59.771 [warn] StdErr from Kernel Process inaccurate.
00:09:59.780 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.780621: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 o
00:09:59.781 [warn] StdErr from Kernel Process utputs. Output shapes may be inaccurate.
00:09:59.861 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.861572: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outpu
00:09:59.861 [warn] StdErr from Kernel Process ts. Output shapes may be inaccurate.
00:09:59.868 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.868779: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output
00:09:59.869 [warn] StdErr from Kernel Process shapes may be inaccurate.
00:09:59.915 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.914985: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:09:59.921 [warn] StdErr from Kernel Process 2023-11-12 00:09:59.921520: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:10:00.173 [warn] StdErr from Kernel Process 2023-11-12 00:10:00.173047: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
2023-11-12 00:10:00
00:10:00.173 [warn] StdErr from Kernel Process .173211: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
00:10:00.175 [warn] StdErr from Kernel Process 2023-11-12 00:10:00.175574: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: C
00:10:00.175 [warn] StdErr from Kernel Process :\Users\BIANCA~1.R\AppData\Local\Temp\tmp_3j_01lm
00:10:00.188 [warn] StdErr from Kernel Process 2023-11-12 00:10:00.188796: I tensorflow/cc/saved_model/reader.cc:91] Reading meta graph with tags { serve }
2023-11-12 00:10:00.188931: I tensorflow/cc/saved_model/reader.cc:132]
00:10:00.189 [warn] StdErr from Kernel Process Reading SavedModel debug info (if present) from: C:\Users\BIANCA~1.R\AppData\Local\Temp
00:10:00.189 [warn] StdErr from Kernel Process \tmp_3j_01lm
00:10:00.235 [warn] StdErr from Kernel Process 2023-11-12 00:10:00.234972: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
00:10:00.244 [warn] StdErr from Kernel Process 2023-11-12 00:10:00.244232: I tensorflow/cc/saved_model/loader.cc:231] Restoring SavedModel bundle.
00:10:00.445 [warn] StdErr from Kernel Process 2023-11-12 00:10:00.445208: I tensorflow/cc/saved_model/loader.cc:215] Running initialization op on SavedModel bundle at path: C:\Users\BIANCA~1.R\AppData\Local\
00:10:00.445 [warn] StdErr from Kernel Process Temp\tmp_3j_01lm
00:10:00.541 [warn] StdErr from Kernel Process 2023-11-12 00:10:0
00:10:00.541 [warn] StdErr from Kernel Process 0.541393: I tensorflow/cc/saved_model/loader.cc:314] SavedModel load for tags { serve }; Status: success: OK. Took 365809 microseconds.
00:10:00.657 [warn] StdErr from Kernel Process 2023-11-12 00:10:00.656653: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
00:10:00.837 [warn] StdErr from Kernel Process loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_28986"("d:\\Anaconda\\
00:10:00.838 [warn] StdErr from Kernel Process Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\
00:10:00.838 [warn] StdErr from Kernel Process \Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\An
00:10:00.838 [warn] StdErr from Kernel Process aconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\L
00:10:00.838 [warn] StdErr from Kernel Process ib\\site-packages\\tensorflow\\lite\\python\\lite.
00:10:00.838 [warn] StdErr from Kernel Process py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\Bianc
00:10:00.838 [warn] StdErr from Kernel Process aa. R\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0))
00:10:00.841 [warn] StdErr from Kernel Process )))))))] at fused["PartitionedCall:", callsite("model_3/lstm_2/PartitionedCall@__inference__wrapped_model_30477"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\
00:10:00.841 [warn] StdErr from Kernel Process Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitionedCall@__inference_signature_wrapper_35000"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-
00:10:00.841 [warn] StdErr from Kernel Process packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\l
00:10:00.842 [warn] StdErr from Kernel Process ite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\
00:10:00.842 [warn] StdErr from Kernel Process Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\T
00:10:00.842 [warn] StdErr from Kernel Process emp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulPart
00:10:00.843 [warn] StdErr from Kernel Process itionedCall:", "StatefulPartitionedCall"])): error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_28986"("d:\\Anaconda\\Li
00:10:00.843 [warn] StdErr from Kernel Process b\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\
00:10:00.843 [warn] StdErr from Kernel Process Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\
00:10:00.843 [warn] StdErr from Kernel Process \Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\sit
00:10:00.843 [warn] StdErr from Kernel Process e-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\
00:10:00.843 [warn] StdErr from Kernel Process \lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lit
00:10:00.843 [warn] StdErr from Kernel Process e.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite
00:10:00.843 [warn] StdErr from Kernel Process .py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\sit
00:10:00.844 [warn] StdErr from Kernel Process e-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))] at fused["PartitionedCall:", callsite("model_3/lstm_2/PartitionedCall@__inf
00:10:00.844 [warn] StdErr from Kernel Process erence__wrapped_model_30477"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\
00:10:00.844 [warn] StdErr from Kernel Process saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\pytho
00:10:00.844 [warn] StdErr from Kernel Process n\\saved_model\\save.py":1280:0 at callsite("d:\\Anac
00:10:00.844 [warn] StdErr from Kernel Process onda\\Lib\\site-packages\\tensorflow\\lite\\
00:10:00.844 [warn] StdErr from Kernel Process python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-pac
00:10:00.844 [warn] StdErr from Kernel Process kages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lit
00:10:00.844 [warn] StdErr from Kernel Process e\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lit
00:10:00.844 [warn] StdErr from Kernel Process e.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.p
00:10:00.844 [warn] StdErr from Kernel Process y":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\42247978
00:10:00.845 [warn] StdErr from Kernel Process 1.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.
00:10:00.845 [warn] StdErr from Kernel Process py":3505:0)))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitionedCall@
00:10:00.845 [warn] StdErr from Kernel Process __inference_signature_wrapper_35000"("d:\\Anaconda\\Lib\\site-packages\\tensorfl
00:10:00.845 [warn] StdErr from Kernel Process ow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages
00:10:00.845 [warn] StdErr from Kernel Process \\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\sit
00:10:00.845 [warn] StdErr from Kernel Process e-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\sit
00:10:00.845 [warn] StdErr from Kernel Process e-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda
00:10:00.845 [warn] StdErr from Kernel Process \\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anac
00:10:00.845 [warn] StdErr from Kernel Process onda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anacon
00:10:00.845 [warn] StdErr from Kernel Process da\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaco
00:10:00.845 [warn] StdErr from Kernel Process nda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Us
00:10:00.846 [warn] StdErr from Kernel Process ers\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at
00:10:00.846 [warn] StdErr from Kernel Process "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)
00:10:00.846 [warn] StdErr from Kernel Process ))))))))]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]))
00:10:00.846 [warn] StdErr from Kernel Process : error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
00:10:00.846 [warn] StdErr from Kernel Process error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
00:10:01.053 [info] End cell 22 execution @ 1699728001053, started @ 1699727989115, elapsed time = 11.938s
00:10:01.053 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:11:14.828 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:11:14.848 [info] Kernel acknowledged execution of cell 22 @ 1699728074848
00:11:23.644 [warn] StdErr from Kernel Process 2023-11-12 00:11:23.646837: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
00:11:23.644 [warn] StdErr from Kernel Process 2023-11-12 00:11:23.647198: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
00:11:24.040 [warn] StdErr from Kernel Process 2023-11-12 00:11:24.043438: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
00:11:24.040 [warn] StdErr from Kernel Process 2023-11-12 00:11:24.043796: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
00:11:36.376 [info] End cell 22 execution @ 1699728096376, started @ 1699728074848, elapsed time = 21.528s
00:11:36.376 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:11:58.296 [info] Handle Execution of Cells 22 for ~\lumin_eye\model1.ipynb
00:11:58.319 [info] Kernel acknowledged execution of cell 22 @ 1699728118319
00:12:07.368 [warn] StdErr from Kernel Process 2023-11-12 00:12:07.380774: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:12:07.702 [warn] StdErr from Kernel Process 2023-11-12 00:12:07.714155: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be i
00:12:07.702 [warn] StdErr from Kernel Process naccurate.
00:12:07.721 [warn] StdErr from Kernel Process 2023-11-12 00:12:07.733322: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be in
00:12:07.721 [warn] StdErr from Kernel Process accurate.
00:12:07.826 [warn] StdErr from Kernel Process 2023-11-12 00:12:07.838116: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may b
00:12:07.826 [warn] StdErr from Kernel Process e inaccurate.
00:12:07.873 [warn] StdErr from Kernel Process 2023-11-12 00:12:07.885928: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attri
00:12:07.874 [warn] StdErr from Kernel Process bute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:12:07.880 [warn] StdErr from Kernel Process 2023-11-12 00:12:07.892327: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:12:07.998 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.010100: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:12:08.012 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.024943: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outpu
00:12:08.013 [warn] StdErr from Kernel Process ts. Output shapes may be inaccurate.
00:12:08.154 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.166211: W
00:12:08.154 [warn] StdErr from Kernel Process tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:12:08.216 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.227972: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:12:08.419 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.431272: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer
00:12:08.419 [warn] StdErr from Kernel Process _helpers.cc:364] Ignored output_format.
2023-11-12 00:12:08.431506: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
00:12:08.419 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.432
00:12:08.420 [warn] StdErr from Kernel Process 185: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmpa_xqlt4d
00:12:08.439 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.451143: I tensorflow/cc/saved_model/r
00:12:08.439 [warn] StdErr from Kernel Process eader.cc:91] Reading meta graph with tags { serve }
2023-11-12 00:12:08.451366: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmpa_x
00:12:08.439 [warn] StdErr from Kernel Process qlt4d
00:12:08.500 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.512397: I tensorflow/cc/saved_model/loader.cc:231] Restoring SavedModel bundle.
00:12:08.704 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.717020: I tensorflow/cc/saved_model/loader.cc:215] Running initial
00:12:08.705 [warn] StdErr from Kernel Process ization op on SavedModel bundle at path: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmpa_xqlt4d
00:12:08.801 [warn] StdErr from Kernel Process 2023-11-12 00:12:08.813838: I tensorflow/cc/saved_model/loader.cc
00:12:08.801 [warn] StdErr from Kernel Process :314] SavedModel load for tags { serve }; Status: success: OK. Took 381646 microseconds.
00:12:09.160 [warn] StdErr from Kernel Process 2023-11-12 00:12:09.172201: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:2073] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexTensorListReserve, FlexTensorListSetItem, FlexTensorListStack
Details:
	tf.TensorListReserve(ten
00:12:09.161 [warn] StdErr from Kernel Process sor<2xi32>, tensor<i32>) -> (tensor<!tf_type.variant<tensor<?x256xf32>>>) : {device = ""}
	tf.TensorListSetItem(tensor<!tf_type.variant<tensor<?x256xf32>>>, tensor<i32>, tensor<?x256xf32>) -> (tensor<!tf_type.variant<tensor<?x256xf32>>>) : {device = "", resize_if_index_out_of_bounds = false}
	tf.TensorListStack(tensor<!tf_type.variant<tensor<?x256xf32>>>, tensor<2xi32>) -> (tensor<1x?x256xf32>) : {device = "", num_elements = 1 : i64}
See instructions: https://www.tensorflow.org/lite/guide/ops_select
00:12:09.415 [info] End cell 22 execution @ 1699728129415, started @ 1699728118319, elapsed time = 11.096s
00:12:19.652 [info] Handle Execution of Cells 23 for ~\lumin_eye\model1.ipynb
00:12:19.668 [info] Kernel acknowledged execution of cell 23 @ 1699728139668
00:12:19.670 [info] End cell 23 execution @ 1699728139670, started @ 1699728139668, elapsed time = 0.002s
00:12:22.613 [info] Handle Execution of Cells 24 for ~\lumin_eye\model1.ipynb
00:12:22.630 [info] Kernel acknowledged execution of cell 24 @ 1699728142630
00:12:22.632 [info] End cell 24 execution @ 1699728142632, started @ 1699728142630, elapsed time = 0.002s
00:12:24.302 [info] Handle Execution of Cells 24 for ~\lumin_eye\model1.ipynb
00:12:24.318 [info] Kernel acknowledged execution of cell 24 @ 1699728144318
00:12:24.321 [info] End cell 24 execution @ 1699728144321, started @ 1699728144318, elapsed time = 0.003s
00:12:28.379 [info] Handle Execution of Cells 25 for ~\lumin_eye\model1.ipynb
00:12:28.396 [info] Kernel acknowledged execution of cell 25 @ 1699728148396
00:18:24.747 [warn] No interpreter for Pylance for Notebook URI "~\lumin_eye\model1_tflite_op.ipynb"
00:18:35.324 [warn] No interpreter for Pylance for Notebook URI "~\lumin_eye\model1_tflite_op.ipynb"
00:21:48.457 [warn] No interpreter for Pylance for Notebook URI "Untitled-1.ipynb"
00:22:23.531 [info] Handle Execution of Cells 0 for Untitled-1.ipynb
00:22:23.534 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd088279d2366fe020547cde40dd65aa0e3aa662a6ec1f3ca12d88834876c85e1a6.d:\Anaconda\python.exe.d:\Anaconda\python.exe.-m#ipykernel_launcher  (Python Path: d:\Anaconda\python.exe, Conda, base, 3.11.4) for 'Untitled-1.ipynb' (disableUI=false)
00:22:34.085 [info] Process Execution: d:\Anaconda\python.exe -m pip list
00:22:34.394 [info] Process Execution: d:\Anaconda\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
00:22:34.438 [info] Process Execution: d:\Anaconda\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"1ec6d405-10f6-4a53-87c7-4e79b08000d6" --shell=9007 --transport="tcp" --iopub=9009 --f="~\AppData\Roaming\jupyter\runtime\kernel-v2-2240FzXGDjKQb210.json"
    > cwd: ~\lumin_eye
00:22:36.049 [info] ipykernel version & path 6.25.0, d:\Anaconda\Lib\site-packages\ipykernel\__init__.py for d:\Anaconda\python.exe
00:22:37.932 [warn] StdErr from Kernel Process 0.02s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
00:22:38.210 [warn] StdErr from Kernel Process d:\Anaconda\Lib\site-packages\traitlets\traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
00:22:38.211 [warn] StdErr from Kernel Process d:\Anaconda\Lib\site-packages\traitlets\traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-2240FzXGDjKQb210.json' instead of '"c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-2240FzXGDjKQb210.json"' if you require traitlets >=5.
00:22:38.671 [info] Kernel acknowledged execution of cell 0 @ 1699728758671
00:22:46.691 [warn] StdErr from Kernel Process 2023-11-12 00:22:46.691180: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow
00:22:46.691 [warn] StdErr from Kernel Process binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX A
00:22:46.691 [warn] StdErr from Kernel Process VX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
00:23:03.096 [warn] StdErr from Kernel Process 2023-11-12 00:23:03.095989: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
00:23:03.096 [warn] StdErr from Kernel Process 2023-11-12 00:23:03.096445: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
00:23:03.658 [warn] StdErr from Kernel Process 2023-11-12 00:23:03.658118: I tensorflow/core/grappler/devices.cc:75] Number of eligible
00:23:03.658 [warn] StdErr from Kernel Process GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
00:23:03.658 [warn] StdErr from Kernel Process 2023-11-12 00:23:03.658735: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
00:23:13.124 [info] End cell 0 execution @ 1699728793124, started @ 1699728758671, elapsed time = 34.453s
00:23:13.124 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:24:32.015 [info] Handle Execution of Cells 0 for Untitled-1.ipynb
00:24:32.021 [info] Kernel acknowledged execution of cell 0 @ 1699728872021
00:24:47.148 [warn] StdErr from Kernel Process 2023-11-12 00:24:47.153574: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate
00:24:47.149 [warn] StdErr from Kernel Process .
00:24:47.273 [warn] StdErr from Kernel Process 2023-11-12 00:24:47.278656: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 ou
00:24:47.274 [warn] StdErr from Kernel Process tputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:24:47.287 [warn] StdErr from Kernel Process 2023-11-12 00:24:47.291876: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:24:47.471 [warn] StdErr from Kernel Process 2023-11-12 00:24:47.476866: W tensorflow/core/common_runtime/graph_constru
00:24:47.472 [warn] StdErr from Kernel Process ctor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:24:47.835 [warn] StdErr from Kernel Process 2023-11-12 00:24:47.840522: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:24:47.862 [warn] StdErr from Kernel Process 2023-11-12 00:24:47.867039: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies
00:24:47.862 [warn] StdErr from Kernel Process shapes for 46 outputs. Output shapes may be inaccurate.
00:24:47.896 [warn] StdErr from Kernel Process 2023-11-12 00:24:47.901590: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shap
00:24:47.896 [warn] StdErr from Kernel Process es may be inaccurate.
00:24:47.910 [warn] StdErr from Kernel Process 2023-11-12 00:24:47.915580: W tensorflow/core/common_runtime/graph_constructor.cc:8
00:24:47.910 [warn] StdErr from Kernel Process 34] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:24:48.073 [warn] StdErr from Kernel Process 2023-11-12 00:24:48.078789: W tensorflow/core/common_runtime/graph_constructor.cc:834
00:24:48.073 [warn] StdErr from Kernel Process ] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:24:48.086 [warn] StdErr from Kernel Process 2023-11-12 00:24:48.091653: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'c
00:24:48.086 [warn] StdErr from Kernel Process ond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
00:24:48.678 [warn] StdErr from Kernel Process 2023-11-12 00:24:48.683747: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
00:24:48.679 [warn] StdErr from Kernel Process 2023-11-12 00:24:48.683945: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
00:24:48.680 [warn] StdErr from Kernel Process 2023-11-12 00:24:
00:24:48.680 [warn] StdErr from Kernel Process 48.686054: I tensorflow/cc/saved_model/r
00:24:48.681 [warn] StdErr from Kernel Process eader.cc:45] Reading SavedModel from:
00:24:48.681 [warn] StdErr from Kernel Process C:\Users\BIANCA~1.R\AppData\Local\Temp\tmp4ylvrppi
00:24:48.705 [warn] StdErr from Kernel Process 2023-11-12 00:24:48.710565: I tensorflow/cc/saved_model/reader.cc:91] Reading meta graph with tags { serve }
2023-11-12 00:24:48.710744: I tensorflow/cc/saved
00:24:48.705 [warn] StdErr from Kernel Process _model/reader.cc:132] Reading SavedModel debug info (if present) from: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmp4ylvrppi
00:24:48.779 [warn] StdErr from Kernel Process 2023-11-12 00:24:48.784236: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
00:24:48.788 [warn] StdErr from Kernel Process 2023-11-12 00:24:48.793631: I tensorflow/cc/saved_model/loader.cc:231] Restoring SavedModel bundle.
00:24:49.082 [warn] StdErr from Kernel Process 2023-11-12 00:24:49.087696: I tensorflow/cc/saved_model/loader.cc:215] Running initia
00:24:49.082 [warn] StdErr from Kernel Process lization op on SavedModel bundle at path: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmp4ylvrppi
00:24:49.218 [warn] StdErr from Kernel Process 2023-11-12 00:24:49.223773: I tensorflow/cc/saved_model/loader.cc:314] SavedModel load for t
00:24:49.219 [warn] StdErr from Kernel Process ags { serve }; Status: success: OK. Took 537717 microseconds.
00:24:49.364 [warn] StdErr from Kernel Process 2023-11-12 00:24:49.370000: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env
00:24:49.365 [warn] StdErr from Kernel Process var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
00:24:49.586 [warn] StdErr from Kernel Process loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_17229"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\sav
00:24:49.586 [warn] StdErr from Kernel Process ed_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\
00:24:49.586 [warn] StdErr from Kernel Process \site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\
00:24:49.586 [warn] StdErr from Kernel Process Lib\\site-packages\\tensorflow\\lit
00:24:49.587 [warn] StdErr from Kernel Process e\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\pytho
00:24:49.587 [warn] StdErr from Kernel Process n\\lite.py":1526:0 at callsite("d:\\Anacond
00:24:49.587 [warn] StdErr from Kernel Process a\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\si
00:24:49.587 [warn] StdErr from Kernel Process te-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_19520\\2779319608.py":9:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0
00:24:49.587 [warn] StdErr from Kernel Process )))))))))] at fused["PartitionedCall:", callsite("model_3/lstm_2/PartitionedCall@__inference__wrapped_mod
00:24:49.588 [warn] StdErr from Kernel Process el_18720"("d:\\Anaconda\\
00:24:49.588 [warn] StdErr from Kernel Process Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\sit
00:24:49.588 [warn] StdErr from Kernel Process e-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib
00:24:49.588 [warn] StdErr from Kernel Process \\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite(
00:24:49.588 [warn] StdErr from Kernel Process "d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packa
00:24:49.589 [warn] StdErr from Kernel Process ges\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\
00:24:49.589 [warn] StdErr from Kernel Process \lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.
00:24:49.589 [warn] StdErr from Kernel Process py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_19520\\2779319608.py":9:0 at "d:\\Anaconda\\Lib\\site-package
00:24:49.589 [warn] StdErr from Kernel Process s\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitioned
00:24:49.590 [warn] StdErr from Kernel Process Call@__inference_signature_wrapper_23243"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\sa
00:24:49.590 [warn] StdErr from Kernel Process ve.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\An
00:24:49.590 [warn] StdErr from Kernel Process aconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda
00:24:49.590 [warn] StdErr from Kernel Process \\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tens
00:24:49.590 [warn] StdErr from Kernel Process orflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tens
00:24:49.591 [warn] StdErr from Kernel Process orflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda
00:24:49.591 [warn] StdErr from Kernel Process \\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\
00:24:49.591 [warn] StdErr from Kernel Process Local\\Temp\\ipykernel_19520\\2779319608.py":9:0 at "d:\\Anaconda\\Lib\\
00:24:49.591 [warn] StdErr from Kernel Process site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))
00:24:49.591 [warn] StdErr from Kernel Process ]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]))
00:24:49.591 [warn] StdErr from Kernel Process : error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
00:24:49.591 [warn] StdErr from Kernel Process loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_l
00:24:49.592 [warn] StdErr from Kernel Process stm_17229"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\pytho
00:24:49.592 [warn] StdErr from Kernel Process n\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packa
00:24:49.592 [warn] StdErr from Kernel Process ges\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda
00:24:49.592 [warn] StdErr from Kernel Process \\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensor
00:24:49.592 [warn] StdErr from Kernel Process flow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site
00:24:49.592 [warn] StdErr from Kernel Process -packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda
00:24:49.592 [warn] StdErr from Kernel Process \\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\
00:24:49.593 [warn] StdErr from Kernel Process \Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.
00:24:49.593 [warn] StdErr from Kernel Process py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\p
00:24:49.593 [warn] StdErr from Kernel Process ython\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Te
00:24:49.593 [warn] StdErr from Kernel Process mp\\ipykernel_19520\\2779319608.py":9:0 at "d:\\Anaconda\\Lib\\
00:24:49.593 [warn] StdErr from Kernel Process site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))
00:24:49.593 [warn] StdErr from Kernel Process ] at fused["PartitionedCall:", callsite("model_3/lstm_2/PartitionedCall@__inference_
00:24:49.593 [warn] StdErr from Kernel Process _wrapped_model_18720"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model
00:24:49.594 [warn] StdErr from Kernel Process \\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("
00:24:49.594 [warn] StdErr from Kernel Process d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\L
00:24:49.595 [warn] StdErr from Kernel Process ib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite(
00:24:49.595 [warn] StdErr from Kernel Process "C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_19520\\2779319608.py":9:0 at "d:\\Anaconda\\Lib
00:24:49.595 [warn] StdErr from Kernel Process \\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulPart
00:24:49.595 [warn] StdErr from Kernel Process itionedCall:", callsite("StatefulPartitionedCall@__inference_signature_wrapper_23243"("
00:24:49.595 [warn] StdErr from Kernel Process d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\
00:24:49.595 [warn] StdErr from Kernel Process save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_
00:24:49.596 [warn] StdErr from Kernel Process model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensor
00:24:49.596 [warn] StdErr from Kernel Process flow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\
00:24:49.596 [warn] StdErr from Kernel Process \lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow
00:24:49.596 [warn] StdErr from Kernel Process \\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite
00:24:49.596 [warn] StdErr from Kernel Process \\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\t
00:24:49.596 [warn] StdErr from Kernel Process ensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\Bianca
00:24:49.597 [warn] StdErr from Kernel Process a. R\\AppData\\Local\\Temp\\ipyker
00:24:49.597 [warn] StdErr from Kernel Process nel_19520\\2779319608.py":9:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulP
00:24:49.597 [warn] StdErr from Kernel Process artitionedCall:", "StatefulPartitionedC
00:24:49.597 [warn] StdErr from Kernel Process all"])): error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
00:24:50.168 [info] End cell 0 execution @ 1699728890168, started @ 1699728872021, elapsed time = 18.147s
00:24:50.168 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:30:34.733 [info] Disposing kernel .jvsc74a57bd088279d2366fe020547cde40dd65aa0e3aa662a6ec1f3ca12d88834876c85e1a6.d:\Anaconda\python.exe.d:\Anaconda\python.exe.-m#ipykernel_launcher for notebook Untitled-1.ipynb due to selection of another kernel or closing of the notebook
00:30:34.733 [info] Dispose Kernel 'Untitled-1.ipynb' associated with 'Untitled-1.ipynb'
00:30:34.734 [info] Dispose Kernel process 19520.
00:30:34.745 [info] Process Execution: c:\WINDOWS\System32\taskkill.exe /F /T /PID 19520
00:40:09.829 [info] End cell 25 execution @ 1699729809829, started @ 1699728148396, elapsed time = 1661.433s
00:40:27.402 [info] Handle Execution of Cells 26 for ~\lumin_eye\model1.ipynb
00:40:27.418 [info] Kernel acknowledged execution of cell 26 @ 1699729827418
00:40:28.171 [info] End cell 26 execution @ 1699729828171, started @ 1699729827418, elapsed time = 0.753s
00:40:30.632 [info] Handle Execution of Cells 27 for ~\lumin_eye\model1.ipynb
00:40:30.649 [info] Kernel acknowledged execution of cell 27 @ 1699729830648
00:40:32.997 [info] End cell 27 execution @ 1699729832996, started @ 1699729830648, elapsed time = 2.348s
00:40:53.551 [info] Handle Execution of Cells 27 for ~\lumin_eye\model1.ipynb
00:40:53.568 [info] Kernel acknowledged execution of cell 27 @ 1699729853568
00:40:55.275 [info] End cell 27 execution @ 1699729855275, started @ 1699729853568, elapsed time = 1.707s
00:41:02.966 [info] Handle Execution of Cells 29 for ~\lumin_eye\model1.ipynb
00:41:02.983 [info] Kernel acknowledged execution of cell 29 @ 1699729862982
00:41:02.987 [info] End cell 29 execution @ 1699729862987, started @ 1699729862982, elapsed time = 0.005s
00:41:02.987 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:41:09.687 [info] Handle Execution of Cells 28 for ~\lumin_eye\model1.ipynb
00:41:09.725 [info] Kernel acknowledged execution of cell 28 @ 1699729869725
00:41:13.233 [info] End cell 28 execution @ 1699729873233, started @ 1699729869725, elapsed time = 3.508s
00:41:15.419 [info] Handle Execution of Cells 29 for ~\lumin_eye\model1.ipynb
00:41:15.433 [info] Kernel acknowledged execution of cell 29 @ 1699729875433
00:41:15.441 [info] End cell 29 execution @ 1699729875441, started @ 1699729875433, elapsed time = 0.008s
00:41:15.441 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:41:18.573 [info] Handle Execution of Cells 29 for ~\lumin_eye\model1.ipynb
00:41:18.586 [info] Kernel acknowledged execution of cell 29 @ 1699729878586
00:41:18.593 [info] End cell 29 execution @ 1699729878593, started @ 1699729878586, elapsed time = 0.007s
00:41:18.593 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:41:31.153 [info] Handle Execution of Cells 29 for ~\lumin_eye\model1.ipynb
00:41:31.169 [info] Kernel acknowledged execution of cell 29 @ 1699729891169
00:41:31.173 [info] End cell 29 execution @ 1699729891173, started @ 1699729891169, elapsed time = 0.004s
00:41:31.173 [warn] Cancel all remaining cells due to cancellation or failure in execution
00:46:35.925 [info] Handle Execution of Cells 24 for ~\lumin_eye\model1.ipynb
00:46:35.963 [info] Kernel acknowledged execution of cell 24 @ 1699730195963
00:46:35.971 [info] End cell 24 execution @ 1699730195970, started @ 1699730195963, elapsed time = 0.007s
00:46:38.914 [info] Handle Execution of Cells 25 for ~\lumin_eye\model1.ipynb
00:46:38.930 [info] Kernel acknowledged execution of cell 25 @ 1699730198930
01:16:52.080 [error] Disposing session as kernel process died ExitCode: 3221226505, Reason: 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
d:\Anaconda\Lib\site-packages\traitlets\traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-2240CDuj5n5In2QN.json' instead of '"c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-2240CDuj5n5In2QN.json"' if you require traitlets >=5.2023-11-11 18:45:26.244815: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-12 00:09:59.046281: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.408846: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.416502: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.659381: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.771492: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.780621: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.861572: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.868779: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.914985: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:09:59.921520: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:10:00.173047: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
2023-11-12 00:10:00.173211: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
2023-11-12 00:10:00.175574: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmp_3j_01lm
2023-11-12 00:10:00.188796: I tensorflow/cc/saved_model/reader.cc:91] Reading meta graph with tags { serve }
2023-11-12 00:10:00.188931: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmp_3j_01lm
2023-11-12 00:10:00.234972: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
2023-11-12 00:10:00.244232: I tensorflow/cc/saved_model/loader.cc:231] Restoring SavedModel bundle.
2023-11-12 00:10:00.445208: I tensorflow/cc/saved_model/loader.cc:215] Running initialization op on SavedModel bundle at path: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmp_3j_01lm
2023-11-12 00:10:00.541393: I tensorflow/cc/saved_model/loader.cc:314] SavedModel load for tags { serve }; Status: success: OK. Took 365809 microseconds.
2023-11-12 00:10:00.656653: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_28986"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))] at fused["PartitionedCall:", callsite("model_3/lstm_2/PartitionedCall@__inference__wrapped_model_30477"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitionedCall@__inference_signature_wrapper_35000"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
loc(callsite(callsite(callsite(fused["TensorListReserve:", callsite("TensorArrayV2_1@__inference_standard_lstm_28986"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))] at fused["PartitionedCall:", callsite("model_3/lstm_2/PartitionedCall@__inference__wrapped_model_30477"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulPartitionedCall:", callsite("StatefulPartitionedCall@__inference_signature_wrapper_35000"("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1313:0) at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\python\\saved_model\\save.py":1280:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1427:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\convert_phase.py":205:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1504:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1526:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1042:0 at callsite("d:\\Anaconda\\Lib\\site-packages\\tensorflow\\lite\\python\\lite.py":1065:0 at callsite("C:\\Users\\<username>\\AppData\\Local\\Temp\\ipykernel_5396\\422479781.py":8:0 at "d:\\Anaconda\\Lib\\site-packages\\IPython\\core\\interactiveshell.py":3505:0)))))))))]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
2023-11-12 00:11:23.646837: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2023-11-12 00:11:23.647198: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-11-12 00:11:24.043438: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2023-11-12 00:11:24.043796: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-11-12 00:12:07.380774: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:07.714155: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:07.733322: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:07.838116: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:07.885928: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:07.892327: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:08.010100: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond/while' has 13 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:08.024943: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:08.166211: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:08.227972: W tensorflow/core/common_runtime/graph_constructor.cc:834] Node 'cond' has 5 outputs but the _output_shapes attribute specifies shapes for 46 outputs. Output shapes may be inaccurate.
2023-11-12 00:12:08.431272: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
2023-11-12 00:12:08.431506: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
2023-11-12 00:12:08.432185: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmpa_xqlt4d
2023-11-12 00:12:08.451143: I tensorflow/cc/saved_model/reader.cc:91] Reading meta graph with tags { serve }
2023-11-12 00:12:08.451366: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmpa_xqlt4d
2023-11-12 00:12:08.512397: I tensorflow/cc/saved_model/loader.cc:231] Restoring SavedModel bundle.
2023-11-12 00:12:08.717020: I tensorflow/cc/saved_model/loader.cc:215] Running initialization op on SavedModel bundle at path: C:\Users\BIANCA~1.R\AppData\Local\Temp\tmpa_xqlt4d
2023-11-12 00:12:08.813838: I tensorflow/cc/saved_model/loader.cc:314] SavedModel load for tags { serve }; Status: success: OK. Took 381646 microseconds.
2023-11-12 00:12:09.172201: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:2073] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexTensorListReserve, FlexTensorListSetItem, FlexTensorListStack
Details:
	tf.TensorListReserve(tensor<2xi32>, tensor<i32>) -> (tensor<!tf_type.variant<tensor<?x256xf32>>>) : {device = ""}
	tf.TensorListSetItem(tensor<!tf_type.variant<tensor<?x256xf32>>>, tensor<i32>, tensor<?x256xf32>) -> (tensor<!tf_type.variant<tensor<?x256xf32>>>) : {device = "", resize_if_index_out_of_bounds = false}
	tf.TensorListStack(tensor<!tf_type.variant<tensor<?x256xf32>>>, tensor<2xi32>) -> (tensor<1x?x256xf32>) : {device = "", num_elements = 1 : i64}
See instructions: https://www.tensorflow.org/lite/guide/ops_select

01:16:52.080 [info] Dispose Kernel process 5396.
01:16:52.113 [info] End cell 25 execution @ undefined, started @ 1699730198930, elapsed time = -1699730198.93s